name: Java CI with Maven

on:
  push:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        
    - name: Build with Maven
      run: mvn clean install
      
    - name: Test with Maven
      run: mvn test
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dwz-jar
        path: target/dwz-0.0.1.jar

